#!/bin/bash
PSQL="psql --username=freecodecamp --dbname=number_guess -t --no-align -c"
SECRET_NUMBER=$(( RANDOM % 1000 + 1 ))

echo -e "\nEnter your username:\n"
read USERNAME

# get user_id
USER_ID=$($PSQL "SELECT user_id FROM user_stories WHERE username='$USERNAME'")

# if not found
if [[ -z $USER_ID ]]
then
  echo "Welcome, $USERNAME! It looks like this is your first time here." | tr -s " "

else
  # pull stats
  GAMES_PLAYED=$($PSQL"SELECT games_played FROM user_stories WHERE user_id=$USER_ID")
  BEST_GAME=$($PSQL "SELECT best_game FROM user_stories WHERE user_id=$USER_ID")
  # welcome back
  echo "Welcome back, $USERNAME! You have played $GAMES_PLAYED games, and your best game took $BEST_GAME guesses." | tr -s " "
fi

GAME_MENU() {
  if [[ $1 ]]
  then
    echo -e "$1"
  fi

  read USER_GUESS
  (( I++ ))
  
  # Not an integer
  if [[ ! $USER_GUESS =~ ^[0-9]+$ ]]
    then
      GAME_MENU "That is not an integer, guess again:"
    
    # Too high
    elif [[ $USER_GUESS -gt $SECRET_NUMBER ]]
    then
      GAME_MENU "It's lower than that, guess again:"

    # Too low
    elif [[ $USER_GUESS -lt $SECRET_NUMBER ]]
    then
      GAME_MENU "It's higher than that, guess again:"
      
    # Correct guess
    elif [[ $USER_GUESS == $SECRET_NUMBER ]]
    then
      echo "You guessed it in $I tries. The secret number was $SECRET_NUMBER. Nice job!"
  fi

}

GAME_MENU "Guess the secret number between 1 and 1000:"

if [[ -z $USER_ID ]]
  then
    # add username
    INSERT_USER=$($PSQL "INSERT INTO user_stories(username,games_played,best_game) VALUES('$USERNAME',1,$I)")

  else
  # Add 1 to games
  (( GAMES_PLAYED++))
  UPDATE_GAMES_PLAYED=$($PSQL "UPDATE user_stories SET games_played=$GAMES_PLAYED WHERE user_id=$USER_ID")

  # compare with best game
  if [[ $I -lt $BEST_GAME ]]
    then
      echo "congratulations, you have a new best score of $I"
      NEW_RECORD=$($PSQL "UPDATE user_stories SET best_game=$I WHERE user_id=$USER_ID")
  fi

fi
